baseURL = 'https://tboggia.github.io/'
languageCode = 'en-us'
title = 'Tommasofolio'
theme = ""
enableGitInfo = true # Useful for showing last updated dates etc.
publishDir = "docs"

[params]
  description = "Despite all attempts at avoiding it, I finally capitulated."

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'